version: '2.2'
services:
  rabbit:
    image: "rabbitmq"
    ports: 
     - "5680:5672"  
  consumer1:
    build: 
      context: .
      dockerfile: consumerDockerfile
    restart: always
    depends_on: 
     - rabbit
  consumer2:
    build: 
      context: .
      dockerfile: consumerDockerfile
    restart: always
    depends_on: 
     - rabbit
